@fill_DinningHall.sql;
@fill_Residential_College;
@fill_Insurance.sql;
@fill_Financial_Service.sql;
@fill_student_service.sql;
@fill_Affiliate.sql;
@fill_Belongs.sql;
@fill_Core.sql;
@fill_Pay_roll.sql;

@fill_Receive.sql;
@fill_Register.sql;
@fill_TA.sql;
@fill_Teach.sql;
@fill_Work_as.sql;
@fill_Purchase_Insurance.sql;
@fill_ClubAdviser.sql;
@fill_Join.sql;
@fill_Spend_DinningPlan.sql;
@fill_live_in.sql;
@fill_Locate.sql;
commit work;
