insert into Spend_DinningPlan (swipeid,student_No,name) values('60001','c0001','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60002','c0002','Hartlay');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60003','c0003','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60004','c0004','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60005','c0005','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60006','c0006','Mudd');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60007','c0007','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60008','c0008','Mudd');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60009','c0009','Hartlay');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60010','c0010','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60011','c0011','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60012','c0012','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60013','c0013','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60014','c0014','Mudd');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60015','c0015','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60016','c0016','Hartlay');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60017','c0017','Hartlay');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60018','c0018','Warlork');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60019','c0019','JJ');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60020','c0020','Warlork');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60021','c0001','JJ');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60022','c0002','JJ');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60023','c0003','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60024','c0005','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60025','c0006','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60026','c0007','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60027','c0008','Mudd');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60028','c0009','Mudd');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60029','c0010','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60030','c0011','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60031','c0012','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60032','c0013','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60033','c0014','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60034','c0015','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60035','c0016','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60036','c0017','Hartlay');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60037','c0018','Warlork');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60038','c0019','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60039','c0020','Warlork');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60040','c0001','JJ');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60041','c0002','JJ');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60042','c0003','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60043','c0004','JJ');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60044','c0005','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60045','c0006','Mudd');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60046','c0007','Hartlay');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60047','c0008','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60048','c0009','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60049','c0010','Unris');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60050','c0011','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60051','c0012','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60052','c0013','JJ');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60053','c0014','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60054','c0015','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60055','c0016','Hartlay');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60056','c0017','Farros Beeth');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60057','c0018','Warlork');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60058','c0019','Cartlon');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60059','c0020','Mudd');
insert into Spend_DinningPlan (swipeid,student_No,name) values('60060','c0020','Farros Beeth');